base/urls.py
from django.urls import path, include
from . import views
from .views import (
    WorkoutAddView, 
    WorkoutUpdateView, 
    WorkoutDeleteView
)

urlpatterns = [
    # The landing page
    path('', views.home, name='home'),

    path('workout/', include([
        # Create and save workouts
        path('add/', WorkoutAddView.as_view(), name='add'),
        path('<int:pk>/fav/', views.fav_add, name='fav_add'),
        path('favorites/', views.workout_favorites, name='workout_favorites'),

        # Workout exercise sets
        path('<int:pk>/', views.view, name='workout_detail'),
        path('<int:pk>/order/', views.save_new_ordering, name='ordering'),
        path('<int:pk>/update/', WorkoutUpdateView.as_view(), name='update'),
        path('<int:pk>/delete/', WorkoutDeleteView.as_view(), name='delete'),

        # Add, edit, delete exercise set
        path('<int:workout_pk>/add/', views.add_exercise, name='add_exercise'),
        path('<int:workout_pk>/<int:exercise_pk>/add/', views.add_exercise, name='add_exercise'),
        path('<int:workout_pk>/<int:exercise_set_pk>/update/', views.exercise_set_update, name='exercise_update'),
        path('<int:workout_pk>/<int:exercise_set_pk>/delete/', views.exercise_set_delete, name='exercise_delete'),
    ])),

    # Calendar view
    path('calendar/', views.workout_calendar, name='workout-calendar'),
    path('calendar/<int:year>/<int:month>/', views.workout_calendar, name='workout-calendar'),
]

fitness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('', include('users.urls')),
    path('exercises/', include('exercises.urls')),
    path('workouts/', include('workouts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workouts/urls.py
from django.urls import path, include
from . import views
from .views import WorkoutPlanListView

urlpatterns = [
    path('', views.workouts_filter, name='workouts-filter'),

    path('programs/', include([
        path('', WorkoutPlanListView.as_view(), name='workout-programs'),
        path('<int:pk>/', views.workoutplan_detail, name='workout-program-detail'),
        path('<int:pk>/unfollow/', views.unfollow_workoutplan, name='workout-program-unfollow'),
        path('<int:pk>/follow/', views.follow_workoutplan, name='workout-program-follow'),
    ])),
]

workouts/models.py
from django.db import models
from PIL import Image
from django.utils import timezone

class WorkoutPlan(models.Model):
    BEGINNER = 'BE'
    INTERMEDIATE = 'IN'
    ADVANCED = 'AD'
    DIFFICULTY = [
        (BEGINNER, 'Beginner'), 
        (INTERMEDIATE, 'Intermediate'),
        (ADVANCED, 'Advanced'),
    ]

    TWO_WEEKS = '2W'
    FOUR_WEEKS = '4W'
    EIGHT_WEEKS = '8W'
    PLANLENGTH = [
        (TWO_WEEKS, '2'), 
        (FOUR_WEEKS, '4'),
        (EIGHT_WEEKS, '8'),
    ]

    THREE_DAYS = '3D'
    FOUR_DAYS = '4D'
    FIVE_DAYS = '5D'
    DAYSPERWEEK = [
        (THREE_DAYS, '3 Days'), 
        (FOUR_DAYS, '4 Days'),
        (FIVE_DAYS, '5 Days'),
    ]

    THIRTY_MIN = '30'
    FOURTYFIVE_MIN = '45'
    SIXTY_MIN = '60'
    TIMEPERWORKOUT = [
        (THIRTY_MIN, '30 Min'), 
        (FOURTYFIVE_MIN, '45 Min'),
        (SIXTY_MIN, '60 Min'),
    ]

    NO_EQ = 'NE'
    DUMBBELL = 'DB'
    GYM = 'GM'
    EQUIPMENT = [
        (NO_EQ, 'No equipment'), 
        (DUMBBELL, 'Dumbbell'),
        (GYM, 'Gym'),
    ]

    LOSE_FAT = 'NE'
    BUILD_MUSCLE = 'DB'
    GET_FIT = 'GM'
    MAINGOAL = [
        (LOSE_FAT, 'Lose Fat'), 
        (BUILD_MUSCLE, 'Build Muscle'),
        (GET_FIT, 'Get Fit'),
    ]
    title = models.CharField(max_length=100)
    difficulty = models.CharField(max_length=100, choices = DIFFICULTY)
    plan_length = models.CharField(max_length=100, choices = PLANLENGTH)
    days_per_week = models.CharField(max_length=100, choices = DAYSPERWEEK)
    time_per_workout = models.CharField(max_length=100, choices = TIMEPERWORKOUT)
    equipment = models.CharField(max_length=100, choices = EQUIPMENT)
    main_goal = models.CharField(max_length=100, choices = MAINGOAL)
    image = models.ImageField(default='default_exercise.jpg', upload_to='program_pics')
    date_posted = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title

    def save(self,*args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 500 or img.width > 500:
            output_size = (500, 500)
            img.thumbnail(output_size)
            img.save(self.image.path)
    
    class Meta:
        ordering = ["-date_posted", ]

workouts/forms.py
from django import forms
from base.models import Workout
from django.forms import ModelForm

class DateInput(forms.DateInput):
    input_type = 'date'

class StartingDateForm(ModelForm): 
    """
    Form for setting a starting date for workout program
    """  
    class Meta:
        model = Workout
        fields = ['workout_day']
        widgets = {'workout_day' : DateInput()}
        labels = {
            "workout_day": ""
        }

workouts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponseRedirect
from base.models import Workout
from .models import WorkoutPlan
from .filter import WorkoutFilter
from .forms import StartingDateForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.list import ListView
from django.contrib import messages
from datetime import date, timedelta

def workouts_filter(request):
    """
    View for looking up workouts by training type (e.g. HIIT, Strength...) and/or body focus (e.g. Upper, Lower body...)
    """
    template_data = {}
    f = WorkoutFilter(request.GET, queryset=Workout.objects.filter(public=True))
    
    workout_list = f.qs
    paginator = Paginator(workout_list, 7)
    page = request.GET.get('page', 1)
    
    try:
        workouts = paginator.page(page)
    except PageNotAnInteger:
        workouts = paginator.page(1)
    except EmptyPage:
        workouts = paginator.page(paginator.num_pages)

    template_data['paginator'] = paginator
    template_data['workouts'] = workouts
    template_data['filter'] = f

    return render(request, 'workouts/workout_filter.html', template_data)

class WorkoutPlanListView(ListView):
    """
    List view of workout programs
    """
    model = WorkoutPlan
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

def workoutplan_detail(request, pk):
    """
    Detail view of workout program

    Users can follow the program by setting a starting date
    The workouts get added to the calendar
    """
    template_data = {}
    plan = get_object_or_404(WorkoutPlan, pk=pk)
    workouts = Workout.objects.filter(workout_plan__id=pk).order_by('plan_week', 'plan_day')

    for workout in workouts:
        if workout.plan_user.filter(username=request.user.username).exists():
            template_data['following'] = True
        else:
            template_data['following'] = False

    if request.method == 'POST':
        form = StartingDateForm(request.POST)
        if form.is_valid():
            starting_date = form.cleaned_data.get('workout_day')
            for workout in workouts:
                if workout.plan_week == 1:
                    if workout.plan_day == 1:
                        workout.plan_user.add(request.user)
                        workout.workout_day = starting_date
                        workout.save()
                    else:
                        workout.plan_user.add(request.user)
                        new_date = starting_date + timedelta(days = workout.plan_day - 1)
                        workout.workout_day = new_date
                        workout.save()
                else:
                    new_day = 7 * (workout.plan_week - 1) + (workout.plan_day - 1)
                    new_date = starting_date + timedelta(days = new_day)
                    workout.plan_user.add(request.user)
                    workout.workout_day = new_date
                    workout.save()
            messages.success(request, f'This workout plan has been added to your calendar')
            return HttpResponseRedirect(reverse('workout-program-detail', kwargs={'pk': pk}))
    else:
        form = StartingDateForm()

    form = StartingDateForm()
    template_data['form'] = form
    template_data['workouts'] = workouts
    template_data['plan'] = plan

    return render(request, 'workouts/workoutplan_detail.html', template_data)

def unfollow_workoutplan(request, pk):
    """
    Unfollow workout program by removing user from the plan users
    """
    workouts_to_update = Workout.objects.filter(workout_plan__id=pk)

    for workout in workouts_to_update:
        workout.plan_user.remove(request.user)
        workout.save()

    messages.success(request, f'You have unsubscribed from this workout plan')
    return HttpResponseRedirect(reverse('workout-program-detail', kwargs={'pk': pk}))

def follow_workoutplan(request, pk):
    """
    Show form in modal to set starting date for workout program
    """
    return render(request, 'workouts/starting_date_form.html')

workouts/templates/workouts/starting_date_form.html
{% load crispy_forms_tags %}
<div class="modal" id="popup_{{plan.id}}" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog w-25 modal-dialog-centered" role="document">
      <div class="modal-content p-3">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Set Starting Date</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-primary" type="submit">Set date</button>
                </div>
            </form>
      </div>
    </div>
</div>

workouts/templates/workouts/workout_filter.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% crispy filter.form filter.form.helper %}
{% load extras %}
{% block content %}
<div class="p-3 pagesize">
    <h1 class="display-4 text-center">Search Workouts</h1>
    <p class="text-center">Find workouts by training type or body focus</p>
    <p class="text-center">
        <i class="lilpadding far fa-user"></i>Other user's workout
        <i class="fas fa-clipboard-list lilpadding pl-4"></i>Included in workout program
    </p>
    <div class="container ">
        <div class="row d-flex justify-content-center">
            <div class="col-10">
                <div class="container">
                    <div class="pt-2">
                        {% if workouts %}    
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                  <th scope="col" class="text-left">Training Type</th>
                                  <th scope="col" class="text-left">Workout Title</th>
                                  <th scope="col" class="text-left">Author</th>
                                </tr>
                              </thead>
                            <tbody>
                                {% for workout in workouts %}
                                    <tr class="table-secondary">
                                        <td class="align-middle text-left p-4">
                                            {% get_type_icon workout.training_type %}
                                        </td>
                                        <td class="align-middle text-left pl-4"><a href="{{ workout.get_absolute_url }}">{{ workout.title }}</a></td>
                                        <td class="align-middle text-left pl-5">
                                            {% if workout.workout_plan %}
                                                <a href="{% url 'workout-program-detail' workout.workout_plan.id %}" class="card-link"><i class="fas fa-clipboard-list lilpadding"></i></a>
                                            {% elif user == workout.user %}
                                                <img src="{{ user.profile.image.url }}" width=20px alt="Profile-Image" class="rounded-circle" title="My workout">
                                            {% else %}
                                                <span title="Other user's workout"><i class="lilpadding far fa-user"></i></span>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% else %}
                            <div>
                                <em><h5>No workouts found</h5></em>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <form method="get">
                    <legend>Filters</legend>
                    <fieldset class="form-group">
                            {{ filter.form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-primary btn-sm" type="submit"><i class="lilpadding fas fa-filter"></i>Filter</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    {% if workouts.has_other_pages %}
        <div class="pt-3">
            <ul class="pagination justify-content-center">
            {% if workouts.has_previous %}
                <li class="page-item"><a class="page-link" href="?{% param_replace page=1 %}">&laquo;</a></li>
                <li class="page-item"><a class="page-link" href="?{% param_replace page=workouts.previous_page_number %}">&lsaquo;</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">&laquo;</a></li>
                <li class="page-item disabled"><a class="page-link" href="#">&lsaquo;</a></li>
            {% endif %}
    
            {% for i in workouts.paginator.page_range %}
                {% if workouts.number == i %}
                    <li class="page-item active">
                        <a class="page-link" href="#"><span>{{ i }} <span class="sr-only">(current)</span></span></a>
                    </li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?{% param_replace page=i %}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
    
            {% if workouts.has_next %}
                <li class="page-item"><a class="page-link" href="?{% param_replace page=workouts.next_page_number %}">&rsaquo;</a></li>
                <li class="page-item"><a class="page-link" href="?{% param_replace page=workouts.paginator.num_pages %}">&raquo;</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">&rsaquo;</a></li>
                <li class="page-item disabled"><a class="page-link" href="#">&raquo;</a></li>
            {% endif %}
            </ul>
        </div>
    {% endif %}
</div>
{% endblock %}

workouts/templates/workouts/workoutplan_detail.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% regroup workouts by plan_week as week_list %}
<h1 class="p-3">{{ plan.title }}</h1>

<div class="p-3">
    <div class="container">
        <div class="row">
            <div class="col-7">
                <h6>Program Details</h6>
                <table class="table text-left">
                    <tbody>
                            <tr>
                                <td class="align-middle">
                                    <i class="fas fa-tachometer-alt lilpadding"></i>Difficulty:
                                </td>
                                <td class="align-middle">
                                    {{ plan.get_difficulty_display }}
                                </td>
                            </tr>
                            <tr>
                                <td class="align-middle">
                                    <i class="fas fa-bullseye lilpadding"></i>Main Goal:
                                </td>
                                <td class="align-middle">
                                    {{ plan.get_main_goal_display }}
                                </td>
                            </tr>
                            <tr>
                                <td class="align-middle">
                                    <i class="far fa-calendar lilpadding"></i>Program Duration:
                                </td>
                                <td class="align-middle">
                                    {{ plan.get_plan_length_display }} Weeks
                                </td>
                            </tr>
                            <tr>
                                <td class="align-middle">
                                    <i class="fas fa-calendar-week lilpadding"></i>Days Per Week:
                                </td>
                                <td class="align-middle">
                                    {{ plan.get_days_per_week_display }}
                                </td>
                            </tr>
                            <tr>
                                <td class="align-middle">
                                    <i class="fas fa-stopwatch lilpadding"></i>Time Per Workout:
                                </td>
                                <td class="align-middle">
                                    {{ plan.get_time_per_workout_display }}
                                </td>
                            </tr>
                            <tr>
                                <td class="align-middle">
                                    <i class="fas fa-tools lilpadding"></i>Equipment Required:
                                </td>
                                <td class="align-middle">
                                    {{ plan.get_equipment_display }}
                                </td>
                            </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-5">
                <h6>Overview</h6>
                <p class="text-justify">{{ plan.description }}</p>
                {% if week_list %}
                <p>
                    {% if following %}
                        <a href="{% url 'workout-program-unfollow' plan.id %}" class="btn btn-danger">Unfollow workout program</a>
                    {% else %}
                        <a class="follow_plan btn btn-success" href="#" data-toggle="modal" data-target="#popup_{{plan.id}}" data-popup-url="{% url 'workout-program-follow' plan.id %}">Follow workout program</a>
                        {% include "workouts/starting_date_form.html" %}
                    {% endif %}
                </p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% if week_list %}
    <div class="pt-3">
        <h6>Program Schedule</h6>
        <small>Rest days inbetween workout days. These could be active rest days.</small>
    </div>

    <div class="container">
        {% for week in week_list %}
            {% if forloop.first %}
                <div class="row">
            {% endif %}
                    <div class="col-4 pcontainter">
                        <div class="card text-left">
                            <div class="card-body">
                                <h4 class="card-title text-center">Week {{ week.grouper }}</h4>
                                <small class="card-subtitle mb-2 text-muted"></small>
                                <p class="card-text">
                                    <table class="table">
                                        <tbody>
                                            {% for workout in workouts %}
                                                {% if week.grouper == workout.plan_week %}
                                                    <tr>
                                                        <td class="align-middle">
                                                            Day {{ workout.plan_day }}: 
                                                        </td>
                                                        <td class="align-middle">
                                                            <a href="{{ workout.get_absolute_url }}">{{ workout.title }}</a>
                                                        </td>
                                                    </tr>
                                                {% endif %}
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </p>
                            </div>
                        </div>
                    </div>
            {% if forloop.counter|divisibleby:3 %}
                </div>
                <div class="row">
            {% endif %}
            {% if forloop.last %}
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% else %}
    <em><h6>Coming soon</h6></em>
{% endif %}

{% endblock %}

{% block script %}
<script>
    $(document).on("click", ".follow_plan", function (e) {
      e.preventDefault();
      var $popup = $("#popup");
      var popup_url = $(this).data("popup-url");
      $(".modal", $popup).load(popup_url, function () {
        $popup.modal("show");
      });
    });
</script>
{% endblock %}

workouts/templates/workouts/workoutplan_list.html
{% extends "base/base.html" %}
{% block content %}
<h1 class="display-2">Workout Programs</h1>

<div class="container">
    {% for plan in object_list %}
        {% if forloop.first %}
            <div class="row">
        {% endif %}
                <div class="col-4 pcontainter">
                    <div class="card text-left">
                        <div class="card-body">
                        <h4 class="card-title"><a href="{% url 'workout-program-detail' plan.id %}">{{ plan }}</a></h4>
                        <h6 class="card-subtitle mb-2 text-muted">{{ plan.get_plan_length_display }} week program - {{ plan.get_time_per_workout_display }}/day</h6>
                        <p class="card-text text-center"><img src="{{ plan.image.url }}" alt="Plan image"></p>
                        <a href="{% url 'workout-program-detail' plan.id %}" class="card-link"><i class="fas fa-info lilpadding"></i>Details</a>
                        <h6 class="float-right text-muted">{{ plan.get_main_goal_display }}</h6>
                        </div>
                    </div>
                </div>
        {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
        {% endif %}
        {% if forloop.last %}
            </div>
        {% endif %}
    {% endfor %}
</div>

{% if page_obj.has_other_pages %}
    <div class="pt-3">
        <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo;</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">&laquo;</a></li>
            <li class="page-item disabled"><a class="page-link" href="#">&lsaquo;</a></li>
        {% endif %}

        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="page-item active">
                    <a class="page-link" href="#"><span>{{ i }} <span class="sr-only">(current)</span></span></a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">&rsaquo;</a></li>
            <li class="page-item disabled"><a class="page-link" href="#">&raquo;</a></li>
        {% endif %}
        </ul>
    </div>
{% endif %}


<footer>
    <div>Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>
</footer>

{% endblock %}