base/urls.py
from django.urls import path, include
from . import views
from .views import (
    WorkoutAddView, 
    WorkoutUpdateView, 
    WorkoutDeleteView
)

urlpatterns = [
    # The landing page
    path('', views.home, name='home'),

    path('workout/', include([
        # Create and save workouts
        path('add/', WorkoutAddView.as_view(), name='add'),
        path('<int:pk>/fav/', views.fav_add, name='fav_add'),
        path('favorites/', views.workout_favorites, name='workout_favorites'),

        # Workout exercise sets
        path('<int:pk>/', views.view, name='workout_detail'),
        path('<int:pk>/order/', views.save_new_ordering, name='ordering'),
        path('<int:pk>/update/', WorkoutUpdateView.as_view(), name='update'),
        path('<int:pk>/delete/', WorkoutDeleteView.as_view(), name='delete'),

        # Add, edit, delete exercise set
        path('<int:workout_pk>/add/', views.add_exercise, name='add_exercise'),
        path('<int:workout_pk>/<int:exercise_pk>/add/', views.add_exercise, name='add_exercise'),
        path('<int:workout_pk>/<int:exercise_set_pk>/update/', views.exercise_set_update, name='exercise_update'),
        path('<int:workout_pk>/<int:exercise_set_pk>/delete/', views.exercise_set_delete, name='exercise_delete'),
    ])),

    # Calendar view
    path('calendar/', views.workout_calendar, name='workout-calendar'),
    path('calendar/<int:year>/<int:month>/', views.workout_calendar, name='workout-calendar'),
]

exercises/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('bank/', views.exercise_filter, name='exercise-filter'),
    path('add/', views.exercise_create, name='exercise-create'),
    path('<int:pk>/', views.exercise_detail, name='exercise-detail'),
]

fitness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('', include('users.urls')),
    path('exercises/', include('exercises.urls')),
    path('workouts/', include('workouts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image
from workouts.models import WorkoutPlan
from django.core.validators import MinValueValidator
from django.utils.translation import gettext_lazy as _

class Workout(models.Model):

    class TrainingType(models.TextChoices):
        HIIT = 'HI', _('HIIT')
        STRENGTH = 'ST'
        YOGA = 'YO'
        CARDIO = 'CA'
        PILATES = 'PA'

    class BodyFocus(models.TextChoices):
        UPPER_BODY = 'UP'
        LOWER_BODY = 'LW'
        CORE = 'CR'
        TOTAL_BODY = 'TL'

    PUBLIC_PRIVATE = (
        (True, 'Every user can view this workout'), 
        (False, 'Only I can view this workout')
    )

    title = models.CharField(max_length=100)
    workout_day = models.DateField(default=date.today)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    training_type = models.CharField(max_length=100, choices = TrainingType.choices)
    body_focus = models.CharField(max_length=100, choices = BodyFocus.choices)
    favorites = models.ManyToManyField(User, related_name='favorite', blank=True)
    public = models.BooleanField(default=True, choices=PUBLIC_PRIVATE)

    workout_plan = models.ForeignKey(WorkoutPlan, blank=True, on_delete=models.SET_NULL, null=True)
    plan_week = models.PositiveIntegerField(blank=True, null=True)
    plan_day = models.PositiveIntegerField(blank=True, null=True)
    plan_user = models.ManyToManyField(User, related_name="workouts", blank=True)

    def __str__(self):
        return f"{self.title} ({self.user}, ID_{self.id})"

    def get_absolute_url(self):
        return reverse('workout_detail', kwargs={'pk': self.pk})

    def is_simple_workout(self):
        return self.training_type in {self.TrainingType.YOGA}

    class Meta:
        ordering = ["-workout_day", ]

class Exercise(models.Model):

    class Focus(models.TextChoices):
        ARMS = 'AR'
        LEGS = 'LG'
        CORE = 'CR'
        BACK = 'BK'
        CHEST = 'CH'
        SHOULDERS = 'SH'
        FULL_BODY = 'FB'
        CARDIO = 'CA'
        YOGA_POSE = 'YP'

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    image = models.ImageField(default='default_exercise.jpg', upload_to='exercise_pics', blank=True)
    description = models.TextField(blank=True)
    focus = models.CharField(max_length = 2, choices=Focus.choices)

    def __str__(self):
        return str(self.name)

    def save(self,*args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 500 or img.width > 500:
            output_size = (500, 500)
            img.thumbnail(output_size)
            img.save(self.image.path)

    class Meta:
        ordering = ["name", ]

class MainExerciseSet(models.Model):
    """
    Base model for types of exercise sets (normal, simple)
    """
    workout = models.ForeignKey(Workout, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    order = models.IntegerField(default=100_000)

    def __str__(self):
        return f"{self.exercise.name}"

    def get_absolute_url(self):
        return reverse('workout_detail', kwargs={'pk': self.pk})

    class Meta():
        ordering = ['order',]

class SimpleExerciseSet(MainExerciseSet):
    """
    Model for simple exercise sets (e.g. Yoga, Pilates)
    """
    def __str__(self):
        return f"{self.workout.title}: {self.exercise.name}"

    class Meta():
        ordering = ['order',]
        
class ExerciseSet(MainExerciseSet):
    """
    Model for normal exercise sets (e.g. Strength, HIIT)
    """
    REP = 'RE'
    SEC = 'SE'
    MIN = 'MN'
    KM = 'KM'
    MILE = 'ML'

    KG = 'KG'
    BODYWEIGHT = 'BW'
    LBS = 'LB'

    REP_OR_SEC = [
        (REP, 'rep(s)'),
        (SEC, 'sec(s)'),
        (MIN, 'minute(s)'),
        (KM, 'km(s)'),
        (MILE, 'mile(s)'),
    ]
    KG_OR_BW = [
        (KG, 'kg'),
        (LBS, 'lbs'),
        (BODYWEIGHT, 'body weight'),
    ]

    DEFAULT_SETS = 4

    set_num = models.PositiveIntegerField(default=DEFAULT_SETS, verbose_name="Number of sets")
    rep_num = models.PositiveIntegerField(verbose_name="Repetitions")
    rep_type = models.CharField(max_length = 2, choices = REP_OR_SEC, default=REP, verbose_name="Unit")
    weight_num = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Weight", default=0, validators=[MinValueValidator(0)])
    weight_type = models.CharField(max_length = 2, choices = KG_OR_BW, default=BODYWEIGHT, verbose_name="Unit")
    rest_time = models.PositiveIntegerField(verbose_name="Rest Time", default=0)

    def __str__(self):
        return f"{self.workout.title} - {self.exercise.name}: {self.set_num} set(s) of {self.rep_num} {self.get_rep_type_display()} {self.weight_num} {self.get_weight_type_display()}"

    def get_absolute_url(self):
        return reverse('workout_detail', kwargs={'pk': self.pk})

    class Meta():
        ordering = ['order',]

exercises/models.py
from django.db import models

# Create your models here.

exercises/forms.py
from django import forms
from base.models import Exercise
from django.forms import ModelForm

class ExerciseCreateForm(forms.ModelForm):
    """
    Form for creating exercise
    """
    blank_choice = [('', 'Choose a focus...')] 
    focus = forms.ChoiceField(choices=blank_choice + Exercise.Focus.choices)
    class Meta:
        model = Exercise
        fields = [
            "name", 
            "image", 
            "description",
            "focus"
        ]

exercises/views.py
from django.shortcuts import render, redirect, get_object_or_404
from base.models import Exercise, Workout
from django.contrib.auth.decorators import login_required
from .filter import ExerciseFilter
from .forms import ExerciseCreateForm
from django.contrib import messages

@login_required
def exercise_filter(request):
    """
    View for looking up exercises by body focus (chest, back, legs, ...)

    User-created workouts are needed for adding exercise through Exercise Bank
    """
    template_data = {}
    focus_names = []
    filter_ = ExerciseFilter(request.GET, queryset=Exercise.objects.all())
    workouts = Workout.objects.filter(user=request.user)

    if filter_:
        values = request.GET.getlist('focus')
        for v in values:
            focus_names.append(Exercise.Focus(v).label)

    template_data['filter'] = filter_
    template_data['workouts'] = workouts
    template_data['focus_names'] = focus_names

    return render(request, 'exercises/exercise_filter.html', template_data)

@login_required
def exercise_create(request):
    """
    View for creating exercises
    """
    if not request.user.is_authenticated:
        return render(request, 'base/index.html')
    else:
        form = ExerciseCreateForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            exercise = form.save(commit=False)
            exercise.user = request.user
            exercise.image = request.FILES['image'] if 'image' in request.FILES else 'default_exercise.jpg'
            exercise.save()
            messages.success(request, f'The exercise has been created')
            return redirect('exercise-filter')
        template_data = {
            "form": form,
        }
        return render(request, 'exercises/exercise_form.html', template_data)

def exercise_detail(request, pk):
    """
    View for exercise detail

    Shows up as modal
    """
    template_data = {}
    exercise = get_object_or_404(Exercise, pk=pk)
    template_data['exercise'] = exercise

    return render(request, 'exercises/exercise_detail.html', template_data)

exercises/templates/exercises/exercise_detail.html
<div class="modal" id="popup_{{exercise.id}}" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="modal-title">{{ exercise.name }}</h3>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div class="d-flex">
            <div class="mr-auto p-1"><img src="{{ exercise.image.url }}" width="300"></div>
            <div class="p-2 text-justify">
                  <h6>Description:</h6>
                  <p>{{ exercise.description }}</p>
                  <h6>Primary muscle group:</h6>
                  <p>{{ exercise.get_focus_display }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

exercises/templates/exercises/exercise_filter.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="w-75 p-3 pagesize">
    <h1 class="text-center display-4">Search Exercises by Body Part</h1>
    <p>Click on the exercise name for details!</p>
    <div class="container">
        <div class="row">
            <div class="col-8">
                {% for obj in filter.qs %}
                    <div class="container">
                        <div class="row align-items-center">
                            <div class="col-3">
                                <img src="{{ obj.image.url }}" width=100px alt="Exercise-Image">
                            </div>
                            <div class="col-6">
                                <h5><a class="open-exercise-detail" href="#" data-toggle="modal" data-target="#popup_{{obj.id}}" data-popup-url="{% url 'exercise-detail' obj.id %}">{{ obj.name }}</a></h5>
                            </div>
                            <div class="col-3">
                                <ul class="dropdown-option">
                                    <li>
                                        <div><i class="fas fa-ellipsis-h"></i></div>
                                        <!-- First level sub dropdown -->
                                        <ul>
                                            {% if workouts %}
                                                <li>
                                                    <div><i class="lilpadding fas fa-plus"></i>Add to workout<i class="fas fa-chevron-right pt-1 float-right"></i></div>
                                                    <!-- Second level sub dropdown -->
                                                    <ul class="p-1">
                                                        {% for workout in workouts %}
                                                            <li><a href="{% url 'add_exercise' workout.id obj.id %}">{{ workout.title }} 
                                                                <small class="text-muted">{{ workout.workout_day|date:"m.d." }}</small>
                                                            </li></a>
                                                        {% endfor %}
                                                    </ul>
                                                </li>
                                            {% endif %}
                                            <li><a class="open-exercise-detail" href="#" data-toggle="modal" data-target="#popup_{{obj.id}}" data-popup-url="{% url 'exercise-detail' obj.id %}"><i class="lilpadding far fa-eye"></i>View details</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    {% include "exercises/exercise_detail.html" with exercise=obj %}
                {% endfor %}
            </div>
            <div class="col-4">
                <div class="pb-2 text-white">
                    {% for focus in focus_names %}
                        <span class="badge bg-dark">{{ focus }}</span>
                    {% endfor %}
                </div>
                <button class="btn btn-dark collapsible"><i class="fas fa-filter lilpadding"></i>Filter</button>
                <div class="content">
                    <p>
                        <form method="get">
                            <fieldset class="form-group">
                                    {{ filter.form|crispy }}
                            </fieldset>
                            <div class="form-group float-right pb-3">
                                <button class="btn btn-secondary btn-sm" type="submit">Filter</button>
                            </div>
                        </form>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;
    
    for (i = 0; i < coll.length; i++) {
      coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.maxHeight){
          content.style.maxHeight = null;
        } else {
          content.style.maxHeight = content.scrollHeight + "px";
        } 
      });
    }
</script>
{% endblock %}

exercises/templates/exercises/exercise_form.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="p-3">
    <div class="formcenter">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Exercise</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Create</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}