base/urls.py
from django.urls import path, include
from . import views
from .views import (
    WorkoutAddView, 
    WorkoutUpdateView, 
    WorkoutDeleteView
)

urlpatterns = [
    # The landing page
    path('', views.home, name='home'),

    path('workout/', include([
        # Create and save workouts
        path('add/', WorkoutAddView.as_view(), name='add'),
        path('<int:pk>/fav/', views.fav_add, name='fav_add'),
        path('favorites/', views.workout_favorites, name='workout_favorites'),

        # Workout exercise sets
        path('<int:pk>/', views.view, name='workout_detail'),
        path('<int:pk>/order/', views.save_new_ordering, name='ordering'),
        path('<int:pk>/update/', WorkoutUpdateView.as_view(), name='update'),
        path('<int:pk>/delete/', WorkoutDeleteView.as_view(), name='delete'),

        # Add, edit, delete exercise set
        path('<int:workout_pk>/add/', views.add_exercise, name='add_exercise'),
        path('<int:workout_pk>/<int:exercise_pk>/add/', views.add_exercise, name='add_exercise'),
        path('<int:workout_pk>/<int:exercise_set_pk>/update/', views.exercise_set_update, name='exercise_update'),
        path('<int:workout_pk>/<int:exercise_set_pk>/delete/', views.exercise_set_delete, name='exercise_delete'),
    ])),

    # Calendar view
    path('calendar/', views.workout_calendar, name='workout-calendar'),
    path('calendar/<int:year>/<int:month>/', views.workout_calendar, name='workout-calendar'),
]

fitness/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('', include('users.urls')),
    path('exercises/', include('exercises.urls')),
    path('workouts/', include('workouts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workouts/urls.py
from django.urls import path, include
from . import views
from .views import WorkoutPlanListView

urlpatterns = [
    path('', views.workouts_filter, name='workouts-filter'),

    path('programs/', include([
        path('', WorkoutPlanListView.as_view(), name='workout-programs'),
        path('<int:pk>/', views.workoutplan_detail, name='workout-program-detail'),
        path('<int:pk>/unfollow/', views.unfollow_workoutplan, name='workout-program-unfollow'),
        path('<int:pk>/follow/', views.follow_workoutplan, name='workout-program-follow'),
    ])),
]

base/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image
from workouts.models import WorkoutPlan
from django.core.validators import MinValueValidator
from django.utils.translation import gettext_lazy as _

class Workout(models.Model):

    class TrainingType(models.TextChoices):
        HIIT = 'HI', _('HIIT')
        STRENGTH = 'ST'
        YOGA = 'YO'
        CARDIO = 'CA'
        PILATES = 'PA'

    class BodyFocus(models.TextChoices):
        UPPER_BODY = 'UP'
        LOWER_BODY = 'LW'
        CORE = 'CR'
        TOTAL_BODY = 'TL'

    PUBLIC_PRIVATE = (
        (True, 'Every user can view this workout'), 
        (False, 'Only I can view this workout')
    )

    title = models.CharField(max_length=100)
    workout_day = models.DateField(default=date.today)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    training_type = models.CharField(max_length=100, choices = TrainingType.choices)
    body_focus = models.CharField(max_length=100, choices = BodyFocus.choices)
    favorites = models.ManyToManyField(User, related_name='favorite', blank=True)
    public = models.BooleanField(default=True, choices=PUBLIC_PRIVATE)

    workout_plan = models.ForeignKey(WorkoutPlan, blank=True, on_delete=models.SET_NULL, null=True)
    plan_week = models.PositiveIntegerField(blank=True, null=True)
    plan_day = models.PositiveIntegerField(blank=True, null=True)
    plan_user = models.ManyToManyField(User, related_name="workouts", blank=True)

    def __str__(self):
        return f"{self.title} ({self.user}, ID_{self.id})"

    def get_absolute_url(self):
        return reverse('workout_detail', kwargs={'pk': self.pk})

    def is_simple_workout(self):
        return self.training_type in {self.TrainingType.YOGA}

    class Meta:
        ordering = ["-workout_day", ]

class Exercise(models.Model):

    class Focus(models.TextChoices):
        ARMS = 'AR'
        LEGS = 'LG'
        CORE = 'CR'
        BACK = 'BK'
        CHEST = 'CH'
        SHOULDERS = 'SH'
        FULL_BODY = 'FB'
        CARDIO = 'CA'
        YOGA_POSE = 'YP'

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    image = models.ImageField(default='default_exercise.jpg', upload_to='exercise_pics', blank=True)
    description = models.TextField(blank=True)
    focus = models.CharField(max_length = 2, choices=Focus.choices)

    def __str__(self):
        return str(self.name)

    def save(self,*args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 500 or img.width > 500:
            output_size = (500, 500)
            img.thumbnail(output_size)
            img.save(self.image.path)

    class Meta:
        ordering = ["name", ]

class MainExerciseSet(models.Model):
    """
    Base model for types of exercise sets (normal, simple)
    """
    workout = models.ForeignKey(Workout, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    order = models.IntegerField(default=100_000)

    def __str__(self):
        return f"{self.exercise.name}"

    def get_absolute_url(self):
        return reverse('workout_detail', kwargs={'pk': self.pk})

    class Meta():
        ordering = ['order',]

class SimpleExerciseSet(MainExerciseSet):
    """
    Model for simple exercise sets (e.g. Yoga, Pilates)
    """
    def __str__(self):
        return f"{self.workout.title}: {self.exercise.name}"

    class Meta():
        ordering = ['order',]
        
class ExerciseSet(MainExerciseSet):
    """
    Model for normal exercise sets (e.g. Strength, HIIT)
    """
    REP = 'RE'
    SEC = 'SE'
    MIN = 'MN'
    KM = 'KM'
    MILE = 'ML'

    KG = 'KG'
    BODYWEIGHT = 'BW'
    LBS = 'LB'

    REP_OR_SEC = [
        (REP, 'rep(s)'),
        (SEC, 'sec(s)'),
        (MIN, 'minute(s)'),
        (KM, 'km(s)'),
        (MILE, 'mile(s)'),
    ]
    KG_OR_BW = [
        (KG, 'kg'),
        (LBS, 'lbs'),
        (BODYWEIGHT, 'body weight'),
    ]

    DEFAULT_SETS = 4

    set_num = models.PositiveIntegerField(default=DEFAULT_SETS, verbose_name="Number of sets")
    rep_num = models.PositiveIntegerField(verbose_name="Repetitions")
    rep_type = models.CharField(max_length = 2, choices = REP_OR_SEC, default=REP, verbose_name="Unit")
    weight_num = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Weight", default=0, validators=[MinValueValidator(0)])
    weight_type = models.CharField(max_length = 2, choices = KG_OR_BW, default=BODYWEIGHT, verbose_name="Unit")
    rest_time = models.PositiveIntegerField(verbose_name="Rest Time", default=0)

    def __str__(self):
        return f"{self.workout.title} - {self.exercise.name}: {self.set_num} set(s) of {self.rep_num} {self.get_rep_type_display()} {self.weight_num} {self.get_weight_type_display()}"

    def get_absolute_url(self):
        return reverse('workout_detail', kwargs={'pk': self.pk})

    class Meta():
        ordering = ['order',]

base/views.py
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.decorators.http import require_POST
from .models import Workout, MainExerciseSet, ExerciseSet, SimpleExerciseSet, Exercise 
from .forms import (
    SetForm, 
    WorkoutForm, 
    SetUpdateForm, 
    OrderingForm, 
    SimpleSetForm, 
    SimpleSetUpdateForm
)
from django.views.generic import (
    CreateView, 
    UpdateView, 
    DeleteView,
)
from django.views import View
from django.http import (
    HttpResponse,
    HttpResponseForbidden, 
    HttpResponseRedirect, 
    JsonResponse,
)
from .helpers import WorkoutCalendar
import datetime
from .filter import WorkoutDateFilter
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.db import transaction

def home(request):
    """ 
    Shows index page
    
    Shows created/followed workouts if user is logged in
    """
    template_data = {}
    user = request.user
    if request.user.is_authenticated:
        date_filter = WorkoutDateFilter(request.GET, queryset=Workout.objects.filter(Q(user=request.user) | Q(plan_user=request.user)))

        workout_list = date_filter.qs
        paginator = Paginator(workout_list, 7)
        page = request.GET.get('page', 1)
        try:
            workouts = paginator.page(page)
        except PageNotAnInteger:
            workouts = paginator.page(1)
        except EmptyPage:
            workouts = paginator.page(paginator.num_pages)
            
        template_data['date_filter'] = date_filter
        template_data['user'] = user
        template_data['paginator'] = paginator
        template_data['workouts'] = workouts 

        return render(request, 'base/home.html', template_data)
    else:
        return render(request, 'base/index.html')

@login_required
def view(request, pk):
    """
    Detail view for workouts
    """
    template_data = {}
    workout = get_object_or_404(Workout, pk=pk)
    exercise = ExerciseSet.objects.filter(workout_id=pk)
    simple_exercise = SimpleExerciseSet.objects.filter(workout_id=pk)
    fav = bool
    user_follows_plan = bool

    if workout.favorites.filter(id=request.user.id).exists():
        fav = True

    if workout.plan_user.filter(id=request.user.id).exists():
        user_follows_plan = True

    template_data['workout'] = workout
    template_data['exercises'] = exercise
    template_data['simple_exercises'] = simple_exercise
    template_data['fav'] = fav
    template_data['user_follows_plan'] = user_follows_plan
    
    return render(request, 'base/detail.html', template_data)

@login_required
def fav_add(request, pk):
    """
    Add workout to favorites / remove from favorites
    """
    workout = get_object_or_404(Workout, pk=pk)
    if workout.favorites.filter(id=request.user.id).exists():
        workout.favorites.remove(request.user)
        messages.success(request, f'{workout.title} has been removed from favorites')
    else:
        workout.favorites.add(request.user)
        messages.success(request, f'{workout.title} has been added to favorites')
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

@login_required
def workout_favorites(request):
    """
    View for the user's favorite workouts
    """
    workouts = Workout.objects.filter(favorites=request.user)
    return render(request, 'base/favorites.html', {'workouts': workouts})

@require_POST
def save_new_ordering(request, pk):
    """
    Order the exercises inside a workout
    """
    form = OrderingForm(request.POST)
    if form.is_valid():
        ordered_ids = form.cleaned_data["ordering"].split(',')

        with transaction.atomic():
            current_order = 1
            for id in ordered_ids:
                exerciseset = MainExerciseSet.objects.get(id__exact=id)
                exerciseset.order = current_order
                exerciseset.save()
                current_order += 1

    return HttpResponseRedirect(reverse('workout_detail', kwargs={'pk': pk}))

@login_required
def workout_calendar(request, year=None, month=None):
    """
    Monthly calendar view of workouts created or followed by user
    """
    template_data = {}

    year = int(year) if year else datetime.date.today().year
    month = int(month) if month else datetime.date.today().month
    prev_month = int(month - 1)
    next_month = int(month + 1)
    workouts = Workout.objects.filter(Q(user=request.user, workout_day__year=year, workout_day__month=month) | 
                                        Q(workout_day__year=year, workout_day__month=month, plan_user=request.user))
    cal = WorkoutCalendar(workouts).formatmonth(year, month)

    template_data['current_year'] = year
    template_data['current_month'] = month
    template_data['prev_month'] = prev_month
    template_data['next_month'] = next_month
    template_data['cal'] = cal
    template_data['workouts'] = workouts

    return render(request, 'base/workout_calendar.html', template_data) 

class WorkoutAddView(LoginRequiredMixin, CreateView):
    """ 
    View to create workout
    """
    model = Workout
    form_class = WorkoutForm

    def form_valid(self, form):
        """
        Set the user this workout belongs to
        """
        form.instance.user = self.request.user
        form.save()
        return super().form_valid(form)

class WorkoutUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    View to update an existing workout
    """
    model = Workout
    form_class = WorkoutForm
    template_name = 'base/workout_update.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        workout = self.get_object()
        if self.request.user == workout.user:
            return True
        return False

class WorkoutDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    Deletes the given workout
    """
    model = Workout
    fields = ['title']
    success_url = '/'

    def test_func(self):
        workout = self.get_object()
        if self.request.user == workout.user:
            return True
        return False

@login_required
def add_exercise(request, workout_pk, exercise_pk=None):
    """ 
    Adds exercise to given workout

    Exercises can be added from the Exercise Bank or with the help of Select2
    Different forms for normal sets (e.g. HIIT, Strength) and simple sets (e.g. Yoga, Pilates)
    """
    template_data = {}

    workout = get_object_or_404(Workout, pk=workout_pk)

    if exercise_pk == None:
        if request.is_ajax():
            term = request.GET.get('term')
            exercises = Exercise.objects.all().filter(name__icontains=term)
            response_content = list(exercises.values())
            return JsonResponse(response_content, safe=False)

        if request.method == 'POST':
            if workout.is_simple_workout():
                set_form = SimpleSetForm(request.POST)
            else:
                set_form  = SetForm(request.POST)

            if set_form.is_valid():
                workout_set = set_form.save(commit=False)
                workout_set.workout_id = workout_pk
                workout_set.save()

                messages.success(request, f'The exercise has been added to the workout')
                return HttpResponseRedirect(reverse('workout_detail', kwargs={'pk': workout.id}))
        else:
            if workout.is_simple_workout():
                set_form = SimpleSetForm()
            else:
                set_form  = SetForm()
    else:
        exercise = get_object_or_404(Exercise, pk=exercise_pk)
        if request.method == 'POST':
            if workout.is_simple_workout():
                set_form = SimpleSetForm(request.POST)
            else:
                set_form  = SetForm(request.POST)

            if set_form.is_valid():
                workout_set = set_form.save(commit=False)
                workout_set.workout_id = workout_pk
                workout_set.save()

                messages.success(request, f'The exercise has been added to the workout')
                return HttpResponseRedirect(reverse('workout_detail', kwargs={'pk': workout.id}))
        else:
            if workout.is_simple_workout():
                set_form = SimpleSetForm(initial={'exercise': exercise }, instance=workout)
            else:
                set_form  = SetForm(initial={'exercise': exercise }, instance=workout)

    template_data['workout'] = workout
    template_data['set_form'] = set_form

    return render(request, 'base/addexercise.html', template_data)

@login_required
def exercise_set_update(request, workout_pk, exercise_set_pk):
    """
    View to edit workout sets
    """
    workout = get_object_or_404(Workout, pk=workout_pk)
    if workout.is_simple_workout():
        exercise_set = get_object_or_404(SimpleExerciseSet, pk=exercise_set_pk)
    else:
        exercise_set = get_object_or_404(ExerciseSet, pk=exercise_set_pk)

    if request.is_ajax():
        term = request.GET.get('term')
        exercises = Exercise.objects.all().filter(name__icontains=term)
        response_content = list(exercises.values())
        return JsonResponse(response_content, safe=False)

    if request.method == 'POST':
        if workout.is_simple_workout():
            u_form = SimpleSetUpdateForm(request.POST, instance=exercise_set)
        else:
            u_form = SetUpdateForm(request.POST, instance=exercise_set)

        if u_form.is_valid():
            u_form.save()
            return HttpResponseRedirect(reverse('workout_detail', kwargs={'pk': workout.id}))
    else:
        if workout.is_simple_workout():

base/templates/base/addexercise.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="p-3">
    <h3>Add exercise to <em>{{ workout.title }}</em></h3>
    <em><a href="{% url 'workouts-filter' %}">Example workouts</a></em> | 
    <em><a href="{% url 'exercise-filter' %}">Example exercises</a></em>
    <div class="w-50 p-3 formcenter">
        {% crispy set_form %}
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    $(document).ready(function () {
        $('#id_exercise').select2({
            placeholder: "Start typing an exercise name...",
            ajax: {
                url: "{% url 'add_exercise' workout.id %}",
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {id: item.id, text: item.name};
                        })
                    };
                }
            },
            minimumInputLength: 1
        });
    });
</script>
{% endblock %}

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Fitness App</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">  
  <!-- Custom CSS -->
  <link href="{% static 'base/bootstrap.css' %}" rel="stylesheet">
  <!-- Free icons -->
  <script src="https://kit.fontawesome.com/b46da477f8.js" crossorigin="anonymous"></script>

  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  
  <!-- Select2 autocomplete -->
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

  {% block style %}
  {% endblock%}
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">Fitness App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav mr-auto">
            <li {% if request.resolver_match.url_name == 'home' %}class="nav-item active"{% endif %} class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
          {% if user.is_authenticated %}
            <li {% if request.resolver_match.url_name == 'workout-calendar' %}class="nav-item active"{% endif %} class="nav-item">
              <a class="nav-link" href="{% url 'workout-calendar' %}">Calendar</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Exercises</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'exercise-filter' %}">Exercise Bank</a>
                <a class="dropdown-item" href="{% url 'exercise-create' %}">Add Exercise</a>
            </li>
            <li {% if request.resolver_match.url_name == 'workouts-filter' %}class="nav-item active"{% endif %} class="nav-item">
              <a class="nav-link" href="{% url 'workouts-filter' %}">Workout Bank</a>
            </li>
            <li {% if request.resolver_match.url_name == 'workout-programs' %}class="nav-item active"{% endif %} class="nav-item">
              <a class="nav-link" href="{% url 'workout-programs' %}">Workout Programs</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li {% if request.resolver_match.url_name == 'profile' %}class="nav-item active"{% endif %} class="nav-item">
              <a class="nav-link" href="{% url 'profile' %}">Profile</a>
            </li>
            <li {% if request.resolver_match.url_name == 'logout' %}class="nav-item active"{% endif %} class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
          </ul>
        {% else %}
        </ul>
          <ul class="nav navbar-nav navbar-right">
            <li {% if request.resolver_match.url_name == 'login' %}class="nav-item active"{% endif %} class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li {% if request.resolver_match.url_name == 'register' %}class="nav-item active"{% endif %} class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
          </ul>
        {% endif %}
    </div>
  </nav>

  <div>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}"> {{ message }}</div>
      {% endfor %}
    {% endif %}
  </div>

  {% block content %}
  {% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<!-- Modal js -->
<script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
<script src="{% static 'base/js/jquery-sortable.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
<script>
  $(document).on("click", ".open-exercise-detail", function (e) {
    e.preventDefault();
    var $popup = $("#popup");
    var popup_url = $(this).data("popup-url");
    $(".modal", $popup).load(popup_url, function () {
      $popup.modal("show");
    });
  });
</script>
{% block script %}
{% endblock %}
</body>
</html>

base/templates/base/exercise_edit.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="p-3">
    <h2>Edit exercise from {{ workout.title }}</h2>
    <div class="w-50 p-3 formcenter">
        {% crispy u_form %}
    </div>
</div>
{% endblock content %}

{% block script %}
<script>
    $(document).ready(function () {
        $('#id_exercise').select2({
            ajax: {
                url: "{% url 'exercise_update' workout.id exercise_set.id %}",
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {id: item.id, text: item.name};
                        })
                    };
                }
            },
            minimumInputLength: 1
        });
    });
</script>
{% endblock %}

base/templates/base/exercise_set_confirm_delete.html
{% extends "base/base.html" %}
{% block content %}
    <div class="w-50 p-3 formcenter">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Exercise</legend>
                <h2>Are you sure you want to delete the exercise "{{ exercise_set.exercise.name }}"?</h2>
            </fieldset>

            <div class="form-group">
                <button type="submit" class="btn btn-danger">Yes, Delete</button>
                <a class="btn btn-secondary" href="{% url 'workout_detail' workout.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

base/templates/base/favorites.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}
{% load extras %}
{% block content %}
<div class="p-3">
    <h1 class="display-4">Favorite workouts</h1>
    <div class="p-2">
        <a href="{% url 'home' %}">Back to your workouts</a>
    </div>  
    {% if workouts %}
        <table class="table table-hover">
            <thead>
                <tr>
                  <th scope="col" class="text-left">Training Type</th>
                  <th scope="col" class="text-left">Workout Title</th>
                  <th scope="col" class="text-left">Workout Day</th>
                  <th scope="col"></th>
                  <th scope="col"></th>
                </tr>
              </thead>
            <tbody>
                {% for workout in workouts %}
                    <tr class="table-secondary">
                        <td class="align-middle text-left p-4">
                            {% get_type_icon workout.training_type %}
                        </td>
                        <td class="align-middle text-left pl-4"><a href="{{ workout.get_absolute_url }}">{{ workout.title }}</a></td>
                        <td class="align-middle text-left pl-4">{{ workout.workout_day|date:"F d, Y" }}
                            <small class="text-muted">{{ workout.workout_day|date:"D" }}</small>
                        </td>
                        <td class="align-middle text-left">
                            {% if user in workout.favorites.all %}
                                <a href="{% url 'fav_add' workout.id %}"><i class="lilpadding fas fa-heart"></i></a>
                            {% else %}
                                <a href="{% url 'fav_add' workout.id %}"><i class="lilpadding far fa-heart"></i></a>
                            {% endif %}
                            {% if workout.workout_plan %}
                                <a href="{% url 'workout-program-detail' workout.workout_plan.id %}" class="card-link"><i class="fas fa-clipboard-list lilpadding"></i>
                            {% endif %}
                        </td>
                        <td class="align-middle">
                            <div class="dropdown">
                                <button class="dropbtn"><i class="fas fa-ellipsis-h"></i></button>
                                <div class="dropdown-content text-left">
                                    <a href="{{ workout.get_absolute_url }}"><i class="lilpadding far fa-eye"></i>Details</a>
                                {% if not workout.workout_plan %}
                                    <a href="{% url 'update' workout.id %}"><i class="lilpadding far fa-edit"></i>Edit</a>
                                    <a href="{% url 'delete' workout.id %}"><i class="lilpadding far fa-trash-alt"></i>Delete</a>
                                {% endif %}
                                </div>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="p-5">
            <em><h5>No workouts found</h5></em>
        </div>
    {% endif %}
</div>
{% endblock content %}

base/templates/base/workout_calendar.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<div class="p-3">
    <h2 class="text-center">Your workout calendar</h2>
        <a href="{% url 'workout-calendar' current_year prev_month %}" class="btn btn-primary btn-sm"><i class="fas fa-chevron-left"></i></a>
        <a href="{% url 'workout-calendar' %}" class="btn btn-primary btn-sm">Current month</a>
        <a href="{% url 'workout-calendar' current_year next_month %}" class="btn btn-primary btn-sm"><i class="fas fa-chevron-right"></i></a>
        <a href="{% url 'add' %}" class="btn btn-primary btn-sm"><i class="lilpadding fas fa-plus-circle"></i>Add workout</a>

    <div class="d-flex justify-content-center text-left" id="workoutcalendar">
        {{ cal|safe }}
    </div>
</div>
{% endblock content %}